"""Initial scheduler schema

Revision ID: 20260921_0001
Revises: 
Create Date: 2026-09-21 14:10:55.601692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260921_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_slot_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('regular_slots', sa.Integer(), nullable=True),
    sa.Column('emergency_enabled', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('override_date')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('allow_emergency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('slot_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_number', name='uq_slot_number')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tenant_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weekly_booking_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tenant_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deployment_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=True),
    sa.Column('jira_change', sa.String(length=64), nullable=True),
    sa.Column('jira_task', sa.String(length=64), nullable=True),
    sa.Column('jira_url', sa.String(length=500), nullable=True),
    sa.Column('change_number', sa.String(length=64), nullable=True),
    sa.Column('work_started_by_user_id', sa.Integer(), nullable=True),
    sa.Column('work_started_at', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('technology', sa.String(length=32), nullable=False),
    sa.Column('requester_name', sa.String(length=120), nullable=False),
    sa.Column('requester_email', sa.String(length=180), nullable=False),
    sa.Column('requester_phone', sa.String(length=40), nullable=True),
    sa.Column('verifier_name', sa.String(length=120), nullable=False),
    sa.Column('verifier_email', sa.String(length=180), nullable=False),
    sa.Column('git_repository', sa.String(length=500), nullable=False),
    sa.Column('implementation_summary', sa.Text(), nullable=False),
    sa.Column('deployment_description', sa.Text(), nullable=False),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('emergency_reason', sa.Text(), nullable=True),
    sa.Column('emergency_approval_reference', sa.String(length=120), nullable=True),
    sa.Column('emergency_approver', sa.String(length=120), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['work_started_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_booking_date', 'deployment_bookings', ['deployment_date'], unique=False)
    op.create_index(op.f('ix_deployment_bookings_created_by_user_id'), 'deployment_bookings', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_deployment_bookings_requester_email'), 'deployment_bookings', ['requester_email'], unique=False)
    op.create_index(op.f('ix_deployment_bookings_tenant_id'), 'deployment_bookings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_deployment_bookings_work_started_by_user_id'), 'deployment_bookings', ['work_started_by_user_id'], unique=False)
    op.create_index('uq_active_slot_per_day', 'deployment_bookings', ['deployment_date', 'slot_number'], unique=True, sqlite_where=sa.text("status <> 'CANCELLED' AND is_emergency = 0"), postgresql_where=sa.text("status <> 'CANCELLED' AND is_emergency = false"))
    op.create_table('slot_freezes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freeze_date', sa.Date(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('freeze_date', 'slot_number', name='uq_slot_freeze_date_number')
    )
    op.create_index('ix_slot_freeze_date', 'slot_freezes', ['freeze_date'], unique=False)
    op.create_table('booking_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['deployment_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'user_id', name='uq_booking_assignment_user')
    )
    op.create_index(op.f('ix_booking_assignments_booking_id'), 'booking_assignments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_assignments_user_id'), 'booking_assignments', ['user_id'], unique=False)
    op.create_table('booking_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['deployment_bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_attachments_booking_id'), 'booking_attachments', ['booking_id'], unique=False)
    op.create_table('booking_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('booking_reference', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('requester_email', sa.String(length=180), nullable=True),
    sa.Column('admin_username', sa.String(length=64), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['deployment_bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_audit_booking_id'), 'booking_audit', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_audit_booking_id'), table_name='booking_audit')
    op.drop_table('booking_audit')
    op.drop_index(op.f('ix_booking_attachments_booking_id'), table_name='booking_attachments')
    op.drop_table('booking_attachments')
    op.drop_index(op.f('ix_booking_assignments_user_id'), table_name='booking_assignments')
    op.drop_index(op.f('ix_booking_assignments_booking_id'), table_name='booking_assignments')
    op.drop_table('booking_assignments')
    op.drop_index('ix_slot_freeze_date', table_name='slot_freezes')
    op.drop_table('slot_freezes')
    op.drop_index('uq_active_slot_per_day', table_name='deployment_bookings', sqlite_where=sa.text("status <> 'CANCELLED' AND is_emergency = 0"), postgresql_where=sa.text("status <> 'CANCELLED' AND is_emergency = false"))
    op.drop_index(op.f('ix_deployment_bookings_work_started_by_user_id'), table_name='deployment_bookings')
    op.drop_index(op.f('ix_deployment_bookings_tenant_id'), table_name='deployment_bookings')
    op.drop_index(op.f('ix_deployment_bookings_requester_email'), table_name='deployment_bookings')
    op.drop_index(op.f('ix_deployment_bookings_created_by_user_id'), table_name='deployment_bookings')
    op.drop_index('ix_booking_date', table_name='deployment_bookings')
    op.drop_table('deployment_bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('slot_configurations')
    op.drop_table('holidays')
    op.drop_table('daily_slot_overrides')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
